export const DISPLAY_IMAGE ='DISPLAY_IMAGE';
export const DISPLAY_SNACKBAR='DISPLAY_SNACKBAR';
export const DISPLAY_ALLBOOKS='DISPLAY_ALLBOOKS'; 
export const DISPLAY_ALLBOOKS_INCART='DISPLAY_ALLBOOKS_INCART';
export const DISPLAY_ALL_SEARCH_BOOKS='DISPLAY_ALL_SEARCH_BOOKS';